### ISSUE TITLE
Incorrect validation performance on imagenet with pretrained model with 0.75 mask ratio

### ISSUE THREAD

**Issue by Xzk7** [bic-L/Masked-Spiking-Transformer#5]
Thanks for your excellent work. We ran the command "torchrun --nproc_per_node=8 main.py --cfg configs/mst/MST.yaml --batch-size 128 --snnvalidate True --dataset imagenet --pretrained ckpt/imagenet_mr_0.75.pth --sim_len 128", then achieved the output accuracy tensor(with size 128) full of 0.001, we did not modify the raw code. Thank you again for your work and time. Look forward to your reply, thank you!

**Comment by bic-L** [comment]
Hi,

We have re-uploaded the checkpoint for Imagenet and updated the readme file. To evaluate performance with a 0.75 masking ratio, please use this command instead:

"torchrun --nproc_per_node=8 main.py --cfg configs/mst/MST.yaml --batch-size 128 --snnvalidate True --dataset imagenet --pretrained ckpt/imagenet_mr_0.75.pth --sim_len 128 --masking_ratio 0.75"

Please let me know if this helps.

**Comment by Xzk7** [comment]
> Hi,
> 
> We have re-uploaded the checkpoint for Imagenet and updated the readme file. To evaluate performance with a 0.75 masking ratio, please use this command instead:
> 
> "torchrun --nproc_per_node=8 main.py --cfg configs/mst/MST.yaml --batch-size 128 --snnvalidate True --dataset imagenet --pretrained ckpt/imagenet_mr_0.75.pth --sim_len 128 --masking_ratio 0.75"
> 
> Please let me know if this helps.

OK, I miss "--masking_ratio 0.75", thanks for your help!
